// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJwr7I7P3Z8dQPYBewPQsvjweoXY4ZQU',
    appId: '1:60884707492:web:a43208d5a011feaca4de31',
    messagingSenderId: '60884707492',
    projectId: 'pemmob-2c6ba',
    authDomain: 'pemmob-2c6ba.firebaseapp.com',
    storageBucket: 'pemmob-2c6ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQXwKDtaIDfp9aULv5QFNmkY8PriUHdo',
    appId: '1:60884707492:android:06322387c6b6f7bfa4de31',
    messagingSenderId: '60884707492',
    projectId: 'pemmob-2c6ba',
    storageBucket: 'pemmob-2c6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPs-oe5DJQchz8VoZYTH80Lf3a0cJZC-A',
    appId: '1:60884707492:ios:640df2df4d720455a4de31',
    messagingSenderId: '60884707492',
    projectId: 'pemmob-2c6ba',
    storageBucket: 'pemmob-2c6ba.appspot.com',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPs-oe5DJQchz8VoZYTH80Lf3a0cJZC-A',
    appId: '1:60884707492:ios:1d041be2034f1749a4de31',
    messagingSenderId: '60884707492',
    projectId: 'pemmob-2c6ba',
    storageBucket: 'pemmob-2c6ba.appspot.com',
    iosBundleId: 'com.example.a.RunnerTests',
  );
}
